VERSION_CODE=10095
VERSION_NAME=1.0.95-beta

GO_VERSION=go1.25.5
KERNEL_UPSTREAM=1.15.0-alpha.6
KERNEL_BRANCH=chain-dev
KERNEL_TAG=v1.15.0-chain.5
KERNEL_COMMIT=a45ff2afcfa6fe2209e31525d1d708bc7276b74b
