VERSION_CODE=10059
VERSION_NAME=1.0.59-beta

GO_VERSION=go1.25.5
KERNEL_UPSTREAM=1.15.0-alpha.5
KERNEL_BRANCH=chain-dev
KERNEL_TAG=v1.15.0-chain.1
KERNEL_COMMIT=5e1593f0f5bf1110a94aab71e55244ceb4ccceba
