package io.nekohasekai.sfa.compose.screen.profileoverride

/**
 * Per-app proxy classification by **network purpose**, not OEM brand.
 *
 * - [NetworkUse.CHINA]: apps that work on the Chinese internet without a
 *   proxy (WeChat, Alipay, banks, mainland stores).
 * - [NetworkUse.FOREIGN]: apps that need an overseas path in China
 *   (Google, Telegram, YouTube, Play Store).
 * - [NetworkUse.SKIP]: device plumbing (AOSP / Samsung / Qualcomm
 *   framework), other VPN/proxy clients, and unknowns. Auto-scan never
 *   selects these — putting telephony/settings through a VPN breaks
 *   networking. The user can still tick an app by hand.
 *
 * Official SagerNet scanned dex for Tencent/Umeng classes and treated
 * every non-hit as overseas, which selected hundreds of system packages.
 * AngelaBox does not sniff dex and does not define overseas as
 * "not China".
 */
object PerAppProxyClassifier {

    enum class NetworkUse { CHINA, FOREIGN, SKIP }

    fun networkUse(
        packageName: String,
        installer: String? = null,
        label: String? = null,
        system: Boolean = false,
    ): NetworkUse {
        val pkg = packageName.trim()
        if (pkg.isEmpty()) return NetworkUse.SKIP
        if (isProxyOrSelf(pkg)) return NetworkUse.SKIP
        if (isDevicePlumbing(pkg)) return NetworkUse.SKIP
        if (pkg in wellKnownForeignPackages) return NetworkUse.FOREIGN
        if (pkg in wellKnownChinaPackages) return NetworkUse.CHINA
        if (system) return NetworkUse.SKIP
        if (isForeignPackageName(pkg)) return NetworkUse.FOREIGN
        if (isChinaPackageName(pkg)) return NetworkUse.CHINA
        if (isChinaInstaller(installer)) return NetworkUse.CHINA
        if (hasChineseLabel(label)) return NetworkUse.CHINA
        return NetworkUse.SKIP
    }

    fun isChinaApp(
        packageName: String,
        installer: String? = null,
        label: String? = null,
        system: Boolean = false,
    ): Boolean = networkUse(packageName, installer, label, system) == NetworkUse.CHINA

    fun isForeignPackage(
        packageName: String,
        installer: String? = null,
        label: String? = null,
        system: Boolean = false,
    ): Boolean = networkUse(packageName, installer, label, system) == NetworkUse.FOREIGN

    fun isChinaPackage(packageName: String): Boolean = isChinaPackageName(packageName.trim())

    internal fun isChinaPackageName(pkg: String): Boolean {
        if (pkg.isEmpty()) return false
        if (isForeignPackageName(pkg) || isDevicePlumbing(pkg) || isProxyOrSelf(pkg)) return false
        if (pkg in wellKnownChinaPackages) return true
        if (pkg.startsWith("cn.") || pkg.contains(".cn.")) return true
        return matchesPrefix(pkg, chinaPrefixes)
    }

    internal fun isForeignPackageName(pkg: String): Boolean {
        if (pkg.isEmpty()) return false
        if (pkg in wellKnownForeignPackages) return true
        return matchesPrefix(pkg, foreignPrefixes)
    }

    internal fun isDevicePlumbing(pkg: String): Boolean {
        if (pkg == "android" || pkg.startsWith("android.")) return true
        if (pkg.contains(".overlay") || pkg.contains(".auto_generated_rro")) return true
        if (matchesPrefix(pkg, plumbingPrefixes)) return true
        if (pkg.startsWith("com.android.")) {
            if (pkg in wellKnownChinaPackages || pkg in wellKnownForeignPackages) return false
            if (matchesPrefix(pkg, chinaPrefixes) || matchesPrefix(pkg, foreignPrefixes)) return false
            return true
        }
        return false
    }

    internal fun isProxyOrSelf(pkg: String): Boolean = matchesPrefix(pkg, proxyPrefixes)

    internal fun isChinaInstaller(installer: String?): Boolean {
        val id = installer?.trim().orEmpty()
        if (id.isEmpty()) return false
        if (id.contains("coolapk", ignoreCase = true)) return true
        return chinaInstallers.any { id == it || id.startsWith("$it.") }
    }

    internal fun hasChineseLabel(label: String?): Boolean {
        val text = label?.trim().orEmpty()
        if (text.isEmpty()) return false
        var han = 0
        var kana = 0
        var hangul = 0
        for (ch in text) {
            when (ch) {
                in '\u4e00'..'\u9fff' -> han++
                in '\u3040'..'\u30ff' -> kana++
                in '\uac00'..'\ud7af' -> hangul++
            }
        }
        return han >= 2 && han > kana && han > hangul
    }

    internal fun matchesPrefix(packageName: String, prefixes: Collection<String>): Boolean {
        for (prefix in prefixes) {
            if (packageName == prefix) return true
            if (prefix.endsWith(".")) {
                if (packageName.startsWith(prefix)) return true
            } else if (packageName.startsWith("$prefix.")) {
                return true
            }
        }
        return false
    }

    private val plumbingPrefixes = listOf(
        "com.samsung",
        "com.sec",
        "com.sem",
        "com.qualcomm",
        "com.qti",
        "com.mediatek",
        "com.trustonic",
        "com.gd.mobicore",
        "com.skms",
        "com.dsi.ant",
        "com.knox",
        "com.wssyncmldm",
        "com.ws.dm",
        "com.android.providers",
        "com.android.systemui",
        "com.android.settings",
        "com.android.phone",
        "com.android.server",
        "com.android.documentsui",
        "com.android.permissioncontroller",
        "com.android.hotwordenrollment",
        "com.android.webview",
        "com.android.bluetooth",
        "com.android.nfc",
        "com.android.stk",
        "com.android.mms",
        "com.android.mtp",
        "com.android.bips",
        "com.android.captiveportallogin",
        "com.android.proxyhandler",
        "com.android.pacprocessor",
        "com.android.location",
        "com.android.keychain",
        "com.android.inputdevices",
        "com.android.wallpaperbackup",
        "com.android.calllogbackup",
        "com.android.managedprovisioning",
        "com.android.statementservice",
        "com.android.carrierdefaultapp",
        "com.android.ons",
        "com.hiya.star",
        "com.google.android.ext",
        "com.google.android.overlay",
        "com.google.android.packageinstaller",
        "com.google.android.partnersetup",
        "com.google.android.backuptransport",
        "com.google.android.setupwizard",
        "com.google.android.configupdater",
        "com.google.android.onetimeinitializer",
        "com.google.android.printservice",
        "com.google.android.gms.policy",
        "com.google.android.apps.restore",
        "com.google.android.networkstack",
        "com.google.android.permissioncontroller",
        "com.google.android.captiveportallogin",
        "com.google.android.syncadapters",
        "com.google.android.webview",
        "com.android.theme",
        "com.android.cts",
        "com.android.shell",
        "com.android.vpndialogs",
        "com.android.internal",
        "com.google.android.as",
        "com.google.android.gsf.login",
    )

    private val proxyPrefixes = listOf(
        "io.chainbox",
        "io.nekohasekai",
        "com.v2ray",
        "com.github.metacubex",
        "com.github.kr328",
        "com.wireguard",
        "com.tailscale",
        "ch.protonvpn",
        "org.outline",
        "com.cloudflare.onedotonedotonedotone",
        "com.cloudflare.cloudflareoneagent",
        "eu.faircode.netguard",
        "com.github.shadowsocks",
        "com.github.shadowsocks.tv",
        "com.hiddify.hiddify",
        "app.hiddify.com",
        "com.v2raytun.android",
        "com.xtls.reality",
        "io.github.trojan_gfw.igniter",
        "de.blinkt.openvpn",
        "net.openvpn.openvpn",
        "org.strongswan.android",
        "org.amnezia.vpn",
        "com.minproxy",
        "com.surfboard",
    )

    private val wellKnownForeignPackages = setOf(
        "ai.x.grok",
        "notion.id",
        "app.revanced.android.gms",
        "com.zhiliaoapp.musically",
        "com.ss.android.ugc.trill",
        "com.ss.android.ugc.aweme.intl",
        "org.telegram.messenger",
        "org.telegram.messenger.web",
        "org.thunderdog.challegram",
        "org.thoughtcrime.securesms",
        "org.mozilla.firefox",
        "org.mozilla.fenix",
        "org.mozilla.focus",
        "org.videolan.vlc",
        "org.fdroid.fdroid",
        "org.wikipedia",
        "org.torproject.torbrowser",
        "com.android.chrome",
        "com.android.vending",
        "com.android.youtube.premium",
        "com.google.android.gm",
        "com.google.android.youtube",
        "com.google.android.apps.maps",
        "com.google.android.apps.photos",
        "com.google.android.calendar",
        "com.google.android.gm.lite",
        "com.microsoft.office.outlook",
        "com.microsoft.skydrive",
        "com.microsoft.office.word",
        "com.microsoft.office.excel",
        "com.microsoft.office.powerpoint",
        "com.microsoft.teams",
        "com.microsoft.copilot",
        "com.spotify.music",
        "com.discord",
        "com.twitter.android",
        "com.facebook.katana",
        "com.facebook.orca",
        "com.instagram.android",
        "com.whatsapp",
        "com.netflix.mediaclient",
        "com.amazon.mShop.android.shopping",
        "com.amazon.avod.thirdpartyclient",
        "com.dropbox.android",
        "com.slack",
        "us.zoom.videomeetings",
        "com.linkedin.android",
        "com.ubercab",
        "com.airbnb.android",
        "com.paypal.android.p2pmobile",
        "jp.naver.line.android",
        "com.skype.raider",
        "com.adobe.reader",
        "com.plexapp.android",
        "com.duolingo",
        "com.brave.browser",
        "com.github.android",
        "com.termux",
        "com.aurora.store",
        "tv.twitch.android.app",
        "com.valvesoftware.android.steam.community",
        "com.nintendo.znba",
        "com.mojang.minecraftpe",
        "com.roblox.client",
        "com.supercell.clashofclans",
        "com.nianticlabs.pokemongo",
        "bbc.mobile.news.ww",
        "com.opera.browser",
        "org.chromium.chrome",
        "com.x.android",
        "com.openai.chatgpt",
        "com.google.android.gms",
        "com.google.android.gsf",
        "com.google.android.googlequicksearchbox",
        "com.google.android.apps.bard",
        "com.google.android.apps.youtube.music",
        "com.google.android.apps.googlevoice",
        "com.google.android.apps.authenticator2",
        "com.google.android.videos",
        "app.revanced.android.youtube",
        "com.vanced.android.youtube",
        "flipboard.boxer.app",
        "com.snapchat.android",
        "com.instagram.barcelona",
        "com.reddit.frontpage",
        "com.duckduckgo.mobile.android",
        "com.microsoft.emmx",
        "com.amazon.kindle",
        "com.disney.disneyplus",
        "com.wbd.stream",
        "com.paramountplus.android",
        "com.anthropic.claude",
        "xyz.blueskyweb.app",
        "org.joinmastodon.android",
        "com.lemon.lvoverseas",
        "com.google.android.apps.docs",
        "com.google.android.apps.tachyon",
        "com.google.android.apps.messaging",
        "com.google.android.dialer",
        "com.google.android.apps.nbu.files",
        "com.google.android.apps.translate",
        "com.google.android.keep",
        "com.google.android.play.games",
        "com.x8bit.bitwarden",
        "com.onepassword.android",
        "com.lastpass.lpandroid",
        "ch.protonmail.android",
        "proton.android.pass",
        "de.tutao.tutanota",
        "com.whatsapp.w4b",
        "com.kakao.talk",
        "jp.pxv.android",
        "com.binance.dev",
        "com.coinbase.android",
        "com.wise.android",
        "com.revolut.revolut",
        "md.obsidian",
        "com.figma.mirror",
        "com.canva.editor",
        "com.bilibili.app.in",
        "tv.danmaku.bilibilihd.intl",
        "org.signal",
        "im.vector.app",
        "com.ubisoft.rainbowsixmobile.fps",
        "com.epicgames.portal",
        "com.gitlab.android",
        "com.miHoYo.GenshinImpact",
        "com.miHoYo.Yuanshencb",
        "com.google.android.projection.gearhead",
    )

    private val foreignPrefixes = listOf(
        "com.google",
        "com.android.chrome",
        "com.android.vending",
        "com.microsoft",
        "com.apple",
        "org.telegram",
        "org.mozilla",
        "org.wikipedia",
        "org.videolan",
        "org.fdroid",
        "org.thoughtcrime",
        "org.torproject",
        "org.thunderdog",
        "org.chromium",
        "org.kde",
        "com.spotify",
        "com.discord",
        "com.reddit",
        "com.twitter",
        "com.facebook",
        "com.instagram",
        "com.whatsapp",
        "com.meta",
        "com.netflix",
        "com.amazon",
        "com.openai",
        "com.anthropic",
        "ai.x",
        "notion.id",
        "com.notion",
        "app.revanced",
        "updated.package.elgoog",
        "com.dropbox",
        "com.slack",
        "us.zoom",
        "com.linkedin",
        "com.ubercab",
        "com.airbnb",
        "com.paypal",
        "jp.naver",
        "com.nintendo",
        "com.sony",
        "com.valvesoftware",
        "tv.twitch",
        "com.adobe",
        "com.plexapp",
        "com.duolingo",
        "com.brave",
        "com.github.android",
        "com.termux",
        "com.aurora",
        "im.vector",
        "com.skype",
        "com.yahoo",
        "com.ebay",
        "com.pinterest",
        "com.shazam",
        "com.soundcloud",
        "com.hbo",
        "com.disney",
        "com.hulu",
        "com.booking",
        "com.tripadvisor",
        "com.ea.gp",
        "com.activision",
        "com.blizzard",
        "com.nianticlabs",
        "com.mojang",
        "com.roblox",
        "com.epicgames",
        "com.supercell",
        "com.opera",
        "com.vivaldi",
        "com.yandex",
        "ru.yandex",
        "com.zhiliaoapp.musically",
        "xyz.nekolab",
        "com.x.android",
        "com.snapchat",
        "com.reddit",
        "com.duckduckgo",
        "xyz.blueskyweb",
        "org.joinmastodon",
        "org.signal",
        "com.lemon.lvoverseas",
        "com.x8bit",
        "com.onepassword",
        "com.lastpass",
        "ch.protonmail",
        "ch.proton",
        "proton.android",
        "de.tutao",
        "com.kakao",
        "com.binance",
        "com.coinbase",
        "com.wise",
        "com.revolut",
        "com.figma",
        "com.canva",
        "md.obsidian",
        "jp.pxv",
        "com.ubisoft",
        "com.epicgames",
        "com.wbd",
        "com.paramountplus",
        "com.paramount",
    )

    internal val wellKnownChinaPackages = setOf(
        "com.tencent.mm",
        "com.tencent.mobileqq",
        "com.tencent.tim",
        "com.tencent.androidqqmail",
        "com.tencent.qqmusic",
        "com.tencent.qqlive",
        "com.tencent.wework",
        "com.tencent.tmgp.sgame",
        "com.tencent.android.qqdownloader",
        "com.eg.android.AlipayGphone",
        "com.unionpay",
        "com.chinatelecom.bestpayclient",
        "cmb.pb",
        "com.icbc",
        "com.chinamworld.main",
        "com.chinamworld.bocmbci",
        "com.android.bankabc",
        "com.yitong.mbank.psbc",
        "com.cgbchina.xpt",
        "com.bankcomm.Bankcomm",
        "cn.com.spdb.mobilebank.per",
        "com.ecitic.bank.mobile",
        "com.cmbchina.ccd.pluto.cmbActivity",
        "com.pingan.paces.ccmsapp",
        "com.cs_credit_bank",
        "com.cebbank.mobile.cemb",
        "com.cib.cibmb",
        "com.cmbc.cc.mbank",
        "com.MobileTicket",
        "cn.gov.tax.its",
        "com.service.android.gov.cn",
        "cn.hsa.app",
        "com.hicorenational.antifraud",
        "com.sankuai.meituan",
        "com.sankuai.meituan.takeoutnew",
        "com.dianping.v1",
        "me.ele",
        "com.xunmeng.pinduoduo",
        "com.taobao.taobao",
        "com.taobao.idlefish",
        "com.taobao.live",
        "com.jingdong.app.mall",
        "com.smile.gifmaker",
        "com.kuaishou.nebula",
        "com.ss.android.ugc.aweme",
        "com.ss.android.ugc.aweme.lite",
        "com.ss.android.article.news",
        "com.ss.android.article.video",
        "com.ss.android.lark",
        "com.alibaba.android.rimet",
        "com.sina.weibo",
        "com.zhihu.android",
        "tv.danmaku.bili",
        "tv.danmaku.bilibilihd",
        "com.baidu.searchbox",
        "com.baidu.BaiduMap",
        "com.baidu.netdisk",
        "com.autonavi.minimap",
        "com.greenpoint.android.mc10086",
        "com.sinovatech.unicom.ui",
        "com.ct.client",
        "ctrip.android.view",
        "com.Qunar",
        "com.sdu.didi.psnger",
        "com.sdu.didi.gsui",
        "com.netease.cloudmusic",
        "com.kugou.android",
        "cn.kuwo.player",
        "com.xingin.xhs",
        "com.achievo.vipshop",
        "com.tmall.wireless",
        "com.alibaba.wireless",
        "com.wudaokou.hippo",
        "com.lianjia.beike",
        "com.anjuke.android.app",
        "com.duokan.phone.remotecontroller",
        "com.miui.weather2",
        "com.xiaomi.smarthome",
        "com.xiaomi.market",
        "com.xiaomi.youpin",
        "com.huawei.health",
        "com.huawei.wallet",
        "com.huawei.appmarket",
        "com.unionpay.tsmservice",
        "com.chinatelecom.selfRegister",
        "com.dragon.read",
        "com.hpbr.bosszhipin",
        "com.tencent.portfolio",
        "com.eastmoney.android.berlin",
        "com.hexin.plat.android",
        "air.tv.douyu.android",
        "com.duowan.kiwi",
        "com.huya.ninja",
        "com.youku.phone",
        "com.qiyi.video",
        "cn.wps.moffice_eng",
        "com.intsig.camscanner",
        "com.coolapk.market",
        "com.netease.newsreader.activity",
        "com.alibaba.android.rimet.aliding",
        "com.sankuai.meituan.dispatch.homebrew",
        "com.taobao.litetao",
        "com.suning.mobile.ebuy",
        "com.smzdm.client.android",
        "com.ximalaya.ting.android",
        "com.tencent.wetype",
        "com.tencent.qqpinyin",
        "com.sohu.inputmethod.sogou",
        "com.baidu.input",
        "com.iflytek.inputmethod",
        "com.tencent.qqmail",
        "com.netease.mobimail",
        "com.chinamobile.mcloud",
        "com.huawei.hidisk",
        "com.mi.health",
        "com.bbk.appstore",
        "com.heytap.market",
        "com.oppo.market",
        "com.meizu.mstore",
        "com.lenovo.leos.appstore",
        "cn.xuexi.android",
        "com.shizhuang.duapp",
        "com.cainiao.wireless",
        "com.quark.browser",
        "com.UCMobile",
        "com.jd.jrapp",
        "com.jingdong.pdj",
        "com.tencent.wemeet.app",
        "com.tencent.map",
        "com.baidu.tieba",
        "com.douban.frodo",
        "com.lemon.lv",
        "com.ss.android.ugc.live",
        "com.ss.android.article.lite",
        "com.tencent.weread",
        "com.qidian.QDReader",
        "com.kmxs.reader",
        "com.tencent.tmgp.pubgmhd",
        "com.miHoYo.Yuanshen",
        "com.icbc.androidclient",
        "cn.gov.pbc.dcep",
        "com.ss.android.auto",
        "com.mt.mtxx.mtxx",
        "com.meitu.meiyancamera",
        "com.sf.activity",
        "com.taobao.qianniu",
        "com.sankuai.meituan.dispatch.crowdsource",
        "com.netease.dwrg",
        "com.kuaishou.sprite",
    )

    private val chinaPrefixes = listOf(
        "com.tencent",
        "com.alibaba",
        "com.alipay",
        "com.taobao",
        "com.tmall",
        "com.ali",
        "com.amap",
        "com.sina",
        "com.weibo",
        "com.vivo",
        "com.xiaomi",
        "com.miui",
        "com.huawei",
        "com.hihonor",
        "com.netease",
        "com.baidu",
        "com.bytedance",
        "com.ss.android",
        "com.kuaishou",
        "com.smile.gifmaker",
        "com.oppo",
        "com.coloros",
        "com.heytap",
        "com.realme",
        "com.oneplus",
        "com.iqoo",
        "com.meizu",
        "com.gionee",
        "cn.nubia",
        "com.oplus",
        "andes.oplus",
        "com.unionpay",
        "cn.wps",
        "com.jingdong",
        "com.jd.",
        "com.sankuai",
        "com.meituan",
        "com.xunmeng",
        "com.eg.android",
        "cmb.pb",
        "com.chinamworld",
        "com.icbc",
        "com.ccb",
        "com.bankcomm",
        "com.cmbchina",
        "com.pingan",
        "com.citic",
        "com.cmbc",
        "com.cib.",
        "com.cgb",
        "com.cebbank",
        "com.psbc",
        "cn.gov",
        "com.gov",
        "com.MobileTicket",
        "ctrip.android",
        "com.sdu.didi",
        "com.didi.",
        "com.xingin",
        "tv.danmaku",
        "com.youku",
        "com.qiyi",
        "com.pplive",
        "com.hunantv",
        "com.duowan",
        "com.meitu",
        "me.ele",
        "com.achievo.vipshop",
        "com.suning",
        "com.smzdm",
        "com.coolapk",
        "com.greenpoint",
        "com.sinovatech",
        "com.ct.client",
        "com.chinamobile",
        "cn.chinaunicom",
        "com.chinatelecom",
        "com.intsig",
        "com.qihoo",
        "com.mx",
        "com.eastmoney",
        "com.hexin",
        "com.foundersc",
        "com.ximalaya",
        "com.duokan",
        "com.lianjia",
        "com.anjuke",
        "com.hpbr",
        "com.sohu",
        "com.iflytek",
        "com.bbk",
        "com.lenovo.leos",
        "cn.goapk",
        "com.dragon.read",
        "com.umeng",
        "com.miHoYo",
        "com.mihoyo",
        "com.lemon.lv",
        "com.quark",
        "com.UCMobile",
        "com.shizhuang",
        "com.cainiao",
        "com.douban",
        "com.qidian",
        "com.kmxs",
        "cn.xuexi",
        "com.sf.activity",
        "com.tencent.wemeet",
        "com.tencent.map",
        "com.tencent.weread",
        "com.jd.jrapp",
        "com.mt.mtxx",
    )

    private val chinaInstallers = listOf(
        "com.xiaomi.market",
        "com.huawei.appmarket",
        "com.oppo.market",
        "com.heytap.market",
        "com.bbk.appstore",
        "com.tencent.android.qqdownloader",
        "com.baidu.appsearch",
        "com.qihoo.appstore",
        "com.dragon.read",
        "com.coolapk.market",
        "com.meizu.mstore",
        "com.lenovo.leos.appstore",
        "cn.goapk.market",
        "com.huawei.appmarket.tv",
        "com.xiaomi.mipicks",
    )
}
